sonar.projectKey=voodoo133_typescript-project-81
sonar.organization=voodoo133

sonar.sources=src
sonar.tests=__tests__
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=src/index.ts